"""AI/BI Dashboard tools for Databricks.

This module provides functions for creating, managing, and deploying
AI/BI dashboards (formerly known as Lakeview dashboards) in Databricks.

The main entry points are CRUD operations for dashboard management.
Dashboard JSON content should be generated by the AI assistant using
the databricks-aibi-dashboards skill documentation.

Example:
    >>> from databricks_tools_core.aibi_dashboards import create_or_update_dashboard
    >>> result = create_or_update_dashboard(
    ...     display_name="Sales Overview",
    ...     parent_path="/Workspace/Users/me/dashboards",
    ...     serialized_dashboard=dashboard_json,  # Generated by AI assistant
    ...     warehouse_id="abc123",
    ... )
    >>> print(result["url"])
"""

from .dashboards import (
    create_dashboard,
    create_or_update_dashboard,
    deploy_dashboard,
    deploy_dashboard_sync,
    find_dashboard_by_path,
    get_dashboard,
    list_dashboards,
    publish_dashboard,
    trash_dashboard,
    unpublish_dashboard,
    update_dashboard,
)
from .models import (
    DashboardDeploymentResult,
)

__all__ = [
    # CRUD operations
    "create_dashboard",
    "get_dashboard",
    "list_dashboards",
    "find_dashboard_by_path",
    "update_dashboard",
    "trash_dashboard",
    "publish_dashboard",
    "unpublish_dashboard",
    # High-level deploy
    "create_or_update_dashboard",
    "deploy_dashboard",
    "deploy_dashboard_sync",
    # Models
    "DashboardDeploymentResult",
]
